site: seeker Blog
title: seeker Blog
description: >-
  just a minimalist, personal blog
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Dhaka
repo: https://github.com/seekermind/seekermind.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Anonymous
  bio: just a minimalist, personal blog
  username: # general username
  github: seekermind # github username
  twitter: # twitter username
  email: seekerApe@protonmail.com # email adress

# URL settings
url: "https://seekermind.github.io/" #
baseurl: "" # leave blank if not wishd
#permalink: "https://seekermind.github.io/Gesko"
#permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


